dev:
  adapter:  PostgreSQL
  database: todomvc
  host:     localhost
  username: adrian
  password: adrian
  port:     5432

prod:
  adapter:
  database:
  host:
  username:
  password:
  port:

test:
  adapter:
  database:
  host:
  username:
  password:
  port:
