dev:
  adapter: PostgreSQL
  database: blogjl_dev
  host: localhost
  username: adrian
  password: adrian
  port: 5432

prod:
  adapter: PostgreSQL
  database: blogjl_dev
  host: localhost
  username: adrian
  password: adrian
  port: 5432

test:
  adapter: PostgreSQL
  database: blogjl_test
  host: localhost
  username: adrian
  password: adrian
  port: 5432
