dev:
  adapter: PostgreSQL
  database: pkg_info_dev
  host: localhost
  username: adrian
  password: adrian
  port: 5432

prod:
  adapter: PostgreSQL
  database: pkg_info_prod
  host: localhost
  username: adrian
  password: adrian
  port: 5432

test:
  adapter: PostgreSQL
  database: pkg_info_test
  host: localhost
  username: adrian
  password: adrian
  port: 5432